


const jobTitles = [
    'Software Developer',
    'Product Manager',
    'Data Scientist',
    'UX/UI Designer',
    'Graphic Designer',
    'Marketing Specialist',
    'Project Manager',
    'Web Developer',
    'DevOps Engineer',
    'QA Tester',
    'Business Analyst',
    'Full Stack Developer',
    'Mobile App Developer',
    'Cloud Architect',
    'Digital Marketing Manager',
    'Content Strategist',
    'System Administrator',
    'Network Engineer',
    'Security Analyst',
    'Game Developer',
    'Data Engineer',
    'AI Researcher',
    'Machine Learning Engineer',
    'Blockchain Developer',
    'Cloud Engineer',
    'Database Administrator',
    'IT Support Specialist',
    'Product Designer',
    'Sales Manager',
    'Customer Success Manager',
    'Operations Manager',
    'Accountant',
    'HR Specialist',
    'Content Writer',
    'Social Media Manager',
    'Public Relations Specialist',
    'Financial Analyst',
    'E-commerce Manager',
    'SEO Specialist',
    'Web Designer',
    'IT Project Manager',
    'Marketing Director',
    'Recruitment Specialist',
    'Legal Advisor',
    'Chief Executive Officer',
    'Chief Technology Officer',
    'Chief Operating Officer',
    'Data Privacy Officer',
    'Business Development Manager',
    'Legal Counsel',
    'Chief Marketing Officer',
    'Healthcare Administrator',
    'Research Scientist',
    'Architect',
    'Operations Coordinator',
    'Event Planner',
    'Salesforce Developer',
    'Database Architect',
    'Virtual Assistant',
    'Copywriter',
    'Financial Planner',
    'Energy Consultant',
    'Environmental Analyst',
    'Supply Chain Manager',
    'Logistics Coordinator',
    'Cybersecurity Specialist',
    'Software Engineer',
    'Talent Acquisition Manager',
    'Nonprofit Manager',
    'Patent Attorney',
    'UX Researcher',
    'Pharmacist',
    'Nurse Practitioner',
    'Marketing Data Analyst',
    'Business Intelligence Analyst',
    'App UI/UX Designer',
    'E-learning Specialist',
    'Public Policy Advisor',
    'Supply Chain Analyst',
    'Legal Consultant',
    'Environmental Engineer',
    'Sustainability Specialist',
    'Retail Manager',
    'Warehouse Manager',
    'Fitness Trainer',
    'Digital Content Creator',
    'Community Manager',
    'Brand Strategist',
    'Healthcare Consultant',
    'Risk Manager',
    'IT Director',
    'Performance Analyst',
    'Creative Director',
    'Film Director',
    'Video Producer',
    'Game Designer',
    '3D Artist',
    'UI Developer',
    'Web Application Architect'
];

const locations = [
    'Texas', 'California', 'New York', 'Florida', 'Illinois', 'Ohio', 'Michigan', 'Georgia', 'North Carolina', 'Pennsylvania',
    'Chicago', 'San Francisco', 'Los Angeles', 'Houston', 'Austin', 'Miami', 'Dallas', 'Seattle', 'Boston', 'Denver'
];


const backgroundImages = [
    'https://www.winnershtriangle.co.uk/wp-content/uploads/2023/06/WT-banner.jpg',
    'https://bendetplant.co.za/wp-content/uploads/analyzing_project_plant_expenses.jpg',
    'https://cdn.prod.website-files.com/655bd943f51b8c3a30acc22e/65e8ea8451d6eb54d307f9e8_65b94984184f367a3a80e21e_What%2520Is%2520the%2520Difference%2520between%2520a%2520Freeway%2520and%2520a%2520Highway.webp',
    'https://images.ctfassets.net/fqtbha7ac6p4/wCuEjVSAM8mCoq9sTo5QC/f5ed83d82cc37670583b774a94f09ac4/Blog-UpToDate__2_.jpg',
    'https://longmontcolorado.gov/wp-content/uploads/2024/07/6335144671_673963a212_o.jpeg',
    'https://cdn.britannica.com/82/156482-131-AEEBFEFC/New-York-York.jpg?w=840&h=460&c=crop',
    'https://images.saymedia-content.com/.image/t_share/MjAwMTUwMjI4Mzc1NDQ2NjM2/disadvantages-of-travelling-by-plane.jpg'
];







export { jobTitles, locations, backgroundImages };